import QtQuick.Controls 2.1
import ArcGIS.AppFramework 1.0

Menu {
    signal deleteGameClicked()

    MenuItem {
        text: qsTr("Delete Game")

        onClicked: deleteGameClicked()
    }

    MenuItem {
        text: qsTr("Mail")

        onClicked: sendMail()
    }

    function sendMail() {
        var params = [
                    [ "subject",
                     "Game Logger: " + currentGameName + " at " + (new Date(currentGameDate)).toLocaleString() ],
                    [ "body",
                     [ "This is email was generated by the Game Logger.",
                      "",
                      "  1. Set To address",
                      "  2. Replace below with Data from Clipboard",
                      "",
                      "<Paste Data from Clipboard Here>",
                      "",
                      "Your's sincerely,",
                      "",
                      "-- Game Logger",
                      "",
                     ].join("\n") + "\n"
                    ]
                ];

        var paramString = params.map( function(e) {
            return e[0] + "=" + encodeURIComponent(e[1])
        } ).join("&");

        var mailUrl = "mailto:?" + paramString;

        var data = [ ];
        data.push("time,text");
        for (var i = 0; i < myDatabase.eventsModel.count; i++) {
            var e = myDatabase.eventsModel.get(i);
            if (e.eventId > 0) {
                data.push( [
                              toCSVString(getTimeString(e.eventTime)),
                              toCSVString(e.eventText)
                          ].join(","));
            }
        }

        AppFramework.clipboard.copy(data.join("\n") + "\n");

        Qt.openUrlExternally(mailUrl);
    }
}
